### ISSUE TITLE
Cant get it working

### ISSUE THREAD

**Issue by Mewzzqt** [crnlskn/ButtplACT#1]
I got a Hush with the bluetooth adapter and it works fine trough their prog but when setting it up in act scanning for devices it doesnt find the plug. i made sure to unblock all the files am i missing something? This is with the latest release

**Comment by Mewzzqt** [comment]
Zie het einde van dit bericht voor meer informatie over het aanroepen 
van JIT-foutopsporing (Just In Time) in plaats van dit dialoogvenster.

************** Tekst van uitzondering **************
System.Reflection.ReflectionTypeLoadException: Kan een of meer van de gevraagde typen niet laden. Haal de LoaderExceptions-eigenschap op voor meer informatie.
   bij System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   bij System.Reflection.Assembly.GetTypes()
   bij System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   bij System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bij Buttplug.Server.DeviceManager.<AddAllSubtypeManagers>d__34.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Buttplug.Server.DeviceManager.<StartScanning>d__33.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Buttplug.Server.DeviceManager.<SendMessageAsync>d__31.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Buttplug.Server.ButtplugServer.<SendMessageAsync>d__31.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Buttplug.Client.ButtplugEmbeddedConnector.<SendAsync>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Buttplug.Client.ButtplugClient.<SendMessageAsync>d__39.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Buttplug.Client.ButtplugClient.<SendMessageExpectOk>d__43.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Buttplug.Client.ButtplugClient.<StartScanningAsync>d__35.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij ButtplACT.PluginSample.<<Button1_ClickAsync>g__StartScanning|48_0>d.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij ButtplACT.PluginSample.<Button1_ClickAsync>d__48.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Geladen assembly's **************
mscorlib
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Advanced Combat Tracker
    Assembly-versie: 3.4.1.261
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Windows.Forms
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3429.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
GammaJul.LgLcd
    Assembly-versie: 1.1.3.0
    Win32-versie: 1.1.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/GammaJul.LgLcd.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly-versie: 0.85.5.452
    Win32-versie: 0.85.5.452
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ICSharpCode.SharpZipLib.DLL
----------------------------------------
mscorlib.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Accessibility
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Serialization
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3440.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3440.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Data
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Trinet.Core.IO.Ntfs
    Assembly-versie: 4.1.1.0
    Win32-versie: 4.1.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Trinet.Core.IO.Ntfs.DLL
----------------------------------------
OverlayPlugin
    Assembly-versie: 0.3.4.0
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
OverlayPlugin.Common
    Assembly-versie: 0.3.4.0
    Win32-versie: 0.3.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/kahouoverlay/OverlayPlugin-0.3.4.0-x64-full/OverlayPlugin.Common.dll
----------------------------------------
OverlayPlugin.Core
    Assembly-versie: 0.3.4.0
    Win32-versie: 0.3.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/kahouoverlay/OverlayPlugin-0.3.4.0-x64-full/OverlayPlugin.Core.dll
----------------------------------------
HtmlRenderer
    Assembly-versie: 1.0.1.8
    Win32-versie: 1.0.1.8
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/kahouoverlay/OverlayPlugin-0.3.4.0-x64-full/HtmlRenderer.dll
----------------------------------------
Xilium.CefGlue
    Assembly-versie: 3.2272.2035.0
    Win32-versie: 3.2272.2035.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/kahouoverlay/OverlayPlugin-0.3.4.0-x64-full/Xilium.CefGlue.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
FFXIV_ACT_Plugin
    Assembly-versie: 2.0.3.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
FFXIV_ACT_Plugin.Memory
    Assembly-versie: 2.0.3.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
FFXIV_ACT_Plugin.Common
    Assembly-versie: 2.0.2.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
FFXIV_ACT_Plugin.Config
    Assembly-versie: 2.0.3.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
FFXIV_ACT_Plugin.LogFile
    Assembly-versie: 2.0.3.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
FFXIV_ACT_Plugin.Network
    Assembly-versie: 2.0.3.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
FFXIV_ACT_Plugin.Overlay
    Assembly-versie: 2.0.3.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
FFXIV_ACT_Plugin.Parse
    Assembly-versie: 2.0.3.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
FFXIV_ACT_Plugin.Resource
    Assembly-versie: 2.0.3.2
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Machina
    Assembly-versie: 2.1.1.1
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Machina.FFXIV
    Assembly-versie: 2.1.3.3
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-versie: 0.0.0.0
    Win32-versie: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Xml.Linq
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
ButtplACT
    Assembly-versie: 0.1.2.0
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Buttplug
    Assembly-versie: 0.5.0.0
    Win32-versie: 0.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Buttplug.DLL
----------------------------------------
NJsonSchema
    Assembly-versie: 10.0.21.0
    Win32-versie: 10.0.21.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/NJsonSchema.DLL
----------------------------------------
Newtonsoft.Json
    Assembly-versie: 12.0.0.0
    Win32-versie: 12.0.2.23222
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Newtonsoft.Json.DLL
----------------------------------------
Newtonsoft.Json
    Assembly-versie: 9.0.0.0
    Win32-versie: 9.0.1.19813
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/kahouoverlay/OverlayPlugin-0.3.4.0-x64-full/Newtonsoft.Json.dll
----------------------------------------
Namotion.Reflection
    Assembly-versie: 1.0.5.0
    Win32-versie: 1.0.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Namotion.Reflection.DLL
----------------------------------------
System.Numerics
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
ButtplACT
    Assembly-versie: 0.1.3.0
    Win32-versie: 3.4.1.261
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Buttplug.Server.Managers.UWPBluetoothManager
    Assembly-versie: 0.5.0.0
    Win32-versie: 0.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Buttplug.Server.Managers.UWPBluetoothManager.DLL
----------------------------------------
Buttplug.Server.Managers.XInputGamepadManager
    Assembly-versie: 0.5.0.0
    Win32-versie: 0.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Buttplug.Server.Managers.XInputGamepadManager.DLL
----------------------------------------
System.Security
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Data.SqlXml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3440.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Transactions
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------

************** JIT-foutopsporing **************
Als u JIT-foutopsporing wilt inschakelen, moet in het configuratiebestand voor deze
toepassing of computer (machine.config) de waarde
jitDebugging in het gedeelte system.windows.forms zijn ingesteld.
De toepassing moet ook zijn gecompileerd terwijl foutopsporing
was ingeschakeld.

Bijvoorbeeld:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wanneer JIT-foutopsporing is ingeschakeld, worden onverwerkte uitzonderingen
naar het JIT-foutopsporingsprogramma gestuurd dat op de computer is geregistreerd
en worden niet door dit dialoogvenster verwerkt.

this is the error message act gives me when scanning for devices sory its  partly dutch

**Comment by Mewzzqt** [comment]
All files are unblocked i made sure also tried it with a seperate folder in the act folder that doesnt work either

**Comment by crnlskn** [comment]
Can you give me a step-by-step description of how exactly you installed it? Is your ACT and ffxiv_plugin up-to-date?

Edit: a few sips of coffee later I notice that you mentioned "the bluetooth adapter" - I take it that means the official lovense adapter?

That one's unfortunately not yet support by buttplug.io, because lovense uses a proprietary protocol to connect via not-quite-normal-bluetooth, as far as I understand. You'd have to get a normal BT4.0/BLE dongle.

**Comment by Mewzzqt** [comment]
BT4.0/BLE dongle. Oh i asumed those wouldnt work as the product says it works with their adapter only due security features.

**Comment by crnlskn** [comment]
Yeah, that's uh, "marketing" I think is the charitable phrasing. There's a [recent defcon talk](https://www.youtube.com/watch?v=CsQ2VWEfduM) about the lovense hardware/software stack.

buttplug.io only supports standard-compliants BLE dongles as far as I understand, and doesn't use any given manufacturer's protocol or security features at all. I'm not sure what kind of vulnerabilities exist in that approach, but it's probably not worse than those that have been described in the aforementioned defcon talk.

**Comment by Mewzzqt** [comment]
Alrighty wil see if i can get one of those dongles then and then see if it works.

**Comment by Mewzzqt** [comment]
Any generic BT4.0 should work or does it also have to be BLE

**Comment by crnlskn** [comment]
[This one](https://www.amazon.com/Plugable-Bluetooth-Adapter-Raspberry-Compatible/dp/B009ZIILLI) is the one recommend by the buttplug.io dev, while [this one](https://www.amazon.de/mumbi-Bluetooth-Dongle-4-0-Reichweite/dp/B011LOJ9QE) is the one I use. There also seem to be issues with at least some aetheros BLE chips, so I'd recommend trying to avoid those.

Edit: oh, and it has to be a BLE-capable device. I don't know whether BT4.0 without BLE exists, but better safe than sorry... :)

**Comment by Mewzzqt** [comment]
[https://www.handyman.nl/product/gembird-bluetooth-mini-usb-dongle-v-4-0/9815012105/](url) What about this ?

**Comment by crnlskn** [comment]
I have no idea, the website is incomprehensible to me because I do not speak the language. I suggest trying to figure out the exact part number of the bluetooth chip and checking whether it's aetheros.

**Comment by crnlskn** [comment]
Closing this because it's really an upstream thing, and here's what upstream has to say:

BCM20702 is one bluetooth chip that definitely works, CSR chips generally seem to work, but unfortunately not many dongles list which chip they use.
