### ISSUE TITLE
Plugin load failure

### ISSUE THREAD

**Issue by ghost** [crnlskn/ButtplACT#9]
Hi! I know this repo hasn't been active for a good long while, but might as well try. I run into a fatal issue as early as trying to load the plugin (this happens both with ButtplACT and your fork of Triggernometry, see attachments). It then throws ACT's generic plugin load error prompt and aborts. Any idea what might be causing this/how to fix it?

https://i.imgur.com/6nz8Fal.png
https://i.imgur.com/luJ0uoj.png
https://i.imgur.com/aw8P2Xj.png

**Comment by crnlskn** [comment]
Hey, sorry, not gonna provide help with anything here, as you maybe noticed I haven't even looked at the github account in a while.
